# Generated by Django 5.0 on 2023-12-31 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_Main_img', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('published_date', models.DateField()),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.author')),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.genre')),
            ],
        ),
    ]
